name: realtime-face-recognition
channels:
  - nvidia
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - cudatoolkit
  - mkl==2024.0
  - pip
  - pip:
      - deep-sort-realtime
      - opencv-python
      - ultralytics
      - mediapipe
      - onnxruntime
      - onnxruntime-gpu
      - deepface
      - tqdm
