name: realtime-face-recognition
channels:
  - nvidia
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - cudatoolkit
  - pip
  - pip:
      - deep-sort-realtime
      - opencv-python
      - ultralytics
      - mediapipe
      - tqdm
      - onnxruntime
