name: realtime-face-recognition
channels:
  - nvidia
  - pytorch
  - anaconda
  - defaults
dependencies:
  # - python=3.8
  # - pytorch
  # - torchvision
  # - torchaudio
  # - pytorch-cuda
  # - cudatoolkit
  # - pip
  # - pip:
  #     - deep-sort-realtime=1.3.2
  #     - opencv-python=4.12.0.88
  #     - ultralytics=8.3.196
  #     - mediapipe=0.10.11
  #     - onnxruntime=1.19.2
  #     - deepface=0.0.95
  #     - tqdm
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - cudatoolkit
  - pip
  - pip:
      - deep-sort-realtime==1.3.2
      - opencv-python==4.12.0.88
      - ultralytics==8.3.198
      - mediapipe==0.10.14
      - onnxruntime==1.22.1
      - onnxruntime-gpu==1.22.0
      - deepface==0.0.95
      - tf-keras==2.20.1
      - tqdm
