## Configuration for the realtime face recognition pipeline.

# Database
database:
    input: "data/raw"
    processed: "data/processed"
    output: "data/embeddings/db.pkl"

# Detector configuration: chọn mô hình phát hiện và đường dẫn file trọng số.
detector:
    name: yolov8
    model_path: "models/detection/yolo/yolov8n-face.pt"
    device: cuda # cuda | cpu | dml
    onnx: false
    providers: ["CUDAExecutionProvider"] # (list) if use onnx: "CUDAExecutionProvider", "CPUExecutionProvider"
    input_size: 640
    conf_thres: 0.25
    iou_thres: 0.45
# Aligner: dùng SimpleResize để chỉ resize và chuẩn hóa ảnh
aligner:
    type: simple
    output_size: [112, 112] # kích thước ảnh align

# Embedding: chọn phương pháp trích xuất đặc trưng.
embedding:
    method: arcface # simple, arcface, deepface
    output_dim: 512 # 512 cho Facenet512/ArcFace, 128 cho Facenet/OpenFace
    input_size: 112
    model_path: "models/embedding/arcface/w600k_r50.onnx" # đường dẫn file .onnx khi dùng ArcFace
    model_name: "ArcFace" # "VGG-Face", "Facenet", "Facenet512", "OpenFace", "DeepFace", "DeepID", "ArcFace", "Dlib", "SFace", "GhostFaceNet", "Buffalo_L"
    enforce_detection: false
    normalize: true
    device: cuda

# Matcher: cấu hình cách so khớp embedding với database.
matcher:
    type: simple
    threshold: 0.5 # Threshold cho cosine similarity với SimpleEmbedder
    use_cosine: true # Cosine similarity cho SimpleEmbedder
    aggregation: topk-mean # max | mean | median | topk-mean
    topk: 3
    second_best_margin: 0.06
    normalize_query: true

# Tracker: chỉ định thuật toán theo dõi và các tham số ByteTrack nếu dùng.
tracker:
    type: bytetrack

    # deepsort
    max_age: 5 # số frame tối đa bỏ lỡ trước khi xoá track
    n_init: 3 # số lần phát hiện liên tiếp để xác nhận track
    max_iou_distance: 0.7 # ngưỡng IOU để ghép detection với track
    embedder_gpu: false # chạy embedder trên GPU (nếu có, cần torch/torchvision)
    half: false # dùng FP16 cho embedder để giảm bộ nhớ
    bgr: true

    # bytetrack
    frame_rate: 30
    track_thresh: 0.5
    match_thresh: 0.8
    min_box_area: 10.0
    use_cuda: False

# Camera: ID của webcam cần sử dụng.
camera:
    device_id: 0
